export const posts = [
    {
        id: 1,
        title: "Title 1",
        img: "https://st3.depositphotos.com/1000423/13229/i/450/depositphotos_132292124-stock-photo-starry-night-and-tree-mixed.jpg",
        desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolore nostrum ad voluptatibus suscipit similique nulla consequuntur quibusdam illo laboriosam quasi soluta praesentium doloremque, amet non aspernatur, sit architecto, saepe quam hic. Harum rem magnam sapiente hic amet! Corrupti ex neque itaque dolorem voluptas ad nesciunt. Error sequi quae blanditiis non ex provident nobis incidunt cum facilis, nostrum aliquid quasi, libero commodi possimus excepturi unde corporis corrupti accusamus aliquam praesentium dignissimos, voluptatibus quaerat pariatur nesciunt! Libero ipsa sint totam voluptatum voluptatem repellat ex facilis labore asperiores officiis quibusdam, nam illo molestias facere reiciendis incidunt veniam recusandae dolores. Amet illum voluptate tenetur!",
        longDesc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ut nam hic quis. Voluptates, quae molestias aperiam consectetur exercitationem laudantium vitae tenetur iure tempora sed temporibus animi rerum veniam vero unde qui, obcaecati dicta. Voluptates ullam ipsam, optio quas totam iure ipsa dolor itaque natus quos repudiandae minus ad numquam eius sit dicta blanditiis? Harum eos aliquid vitae quo cumque impedit tenetur dolore consequuntur aliquam ad obcaecati mollitia eum officiis, labore praesentium, incidunt accusantium est molestias dolorum delectus? Nemo aspernatur et maxime dolore laboriosam distinctio. Eligendi quod non quidem alias enim illum saepe, amet ullam nulla laborum, accusantium voluptatem velit repudiandae eius minima debitis error reprehenderit! Culpa maxime, totam porro inventore facilis hic non cupiditate vel id dignissimos ab, voluptatem corrupti autem, quam saepe explicabo excepturi libero nam sit fugit dolor asperiores perferendis. Voluptates, eligendi cum! Enim vel doloremque nemo, earum et porro autem iure beatae adipisci in, aperiam ex deleniti impedit quia perferendis dolorum modi officia, ab aut ad facere perspiciatis exercitationem! Aliquid illo facere repellendus odio laudantium! Sed sequi quidem doloribus eveniet neque aspernatur aperiam ipsam illum quod laboriosam, voluptatibus eos ex rem, tenetur fuga tempora ullam dolores! Dolorum quasi alias consequatur repellat quidem error aliquid magnam doloremque adipisci obcaecati quos consequuntur, velit non quisquam temporibus enim voluptatum unde nostrum explicabo! Voluptatem magnam accusantium dolorem nemo pariatur, iure et molestias ut a esse quia! Soluta amet, id magnam sunt modi rerum tempore. Ipsam numquam quas itaque mollitia corrupti ullam eos tempore nemo ducimus laudantium nam, eum, recusandae ut unde aut consequatur molestiae ea facilis consequuntur cumque! Expedita voluptatum dolor consectetur. Similique adipisci aperiam reiciendis nisi consequatur, quis impedit commodi a dolores sint, maxime natus sed. Necessitatibus ut, sed ullam, neque harum quisquam, ad molestias voluptatum esse ipsam sunt omnis vitae voluptatibus aliquam laudantium animi error expedita magni dolore! Tenetur."
    },
    {
        id: 2,
        title: "Title 2",
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_960_720.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta illum hic maxime alias libero saepe non amet error ex aperiam placeat nobis nostrum eveniet, porro obcaecati unde dolor dicta natus sapiente veritatis excepturi reiciendis iste. Perspiciatis dicta, sequi voluptatem ratione dolore, cum assumenda deserunt nostrum dolores voluptas quis. Dolorum quia commodi expedita doloribus, dolore, repudiandae fuga eos veniam inventore necessitatibus in sequi, aliquam facilis dolor non odio perferendis. Adipisci, repellat voluptatem! Illo officiis, officia quis numquam obcaecati eaque iure temporibus molestias perferendis amet iste ad laboriosam dolor impedit, molestiae facilis rem enim magni recusandae veniam ipsa ea. Odit, officiis dicta.",
        longDesc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum quos laudantium doloribus, impedit eligendi, corrupti ipsum molestiae at voluptas itaque asperiores accusamus esse voluptatum laborum. Porro odit exercitationem tempora quis, reiciendis ipsum, architecto aut perspiciatis eius fugiat cumque suscipit fugit provident. Corporis distinctio ipsum dolore fugit. Sint, ad voluptates nemo facilis quisquam perferendis aut natus ratione minus, debitis, itaque ab officia magnam repudiandae similique. Molestiae quidem quia animi tempora praesentium. Doloremque, ipsa quo! Voluptate iure cum unde culpa facere nihil iste rerum praesentium atque fugiat laboriosam inventore incidunt natus dolores dolor doloribus cumque non deserunt veniam similique architecto, eligendi animi. Unde debitis perspiciatis officia. Modi, iste rem culpa earum rerum eius optio et sunt ab! Pariatur laudantium consequuntur non? Numquam reiciendis ad accusamus! Saepe, necessitatibus sapiente ea inventore ipsa, quas libero, excepturi minima tempora voluptate corrupti nihil et suscipit. Accusantium dolores reprehenderit porro. Non tempore quos exercitationem nesciunt, earum veniam quaerat doloribus minus eveniet, amet ad aspernatur similique repellat neque. Nam veritatis tempora sint quidem? Cumque voluptatum minima modi ducimus quidem nesciunt, voluptatem blanditiis eum sit accusantium molestias minus reiciendis sed praesentium eos eveniet quia sint quis! Autem nisi quasi inventore placeat sunt ratione debitis, atque porro temporibus. Vero ipsa dolor quisquam ut, veniam, nemo dolorem a sint iusto voluptatem soluta. Repellat possimus dolores fuga at! Reprehenderit, aliquam rem. Hic odio vero libero exercitationem molestias nobis sed at ad. Hic voluptatibus, beatae voluptatem laboriosam aut ipsa sapiente quaerat quidem incidunt magni maiores labore sint, eum nisi culpa harum sequi quos? Explicabo eum rerum, distinctio eos voluptatibus ipsa fugiat, provident laboriosam excepturi dignissimos laudantium necessitatibus impedit doloribus similique dolor dolores nam, sed ducimus est illo numquam. Perferendis praesentium tempore culpa unde nobis eaque impedit, enim quam natus? Exercitationem cupiditate iste ipsum illo consequatur atque vero eveniet fugiat a, nam dolore quibusdam."
    },
    {
        id: 3,
        title: "Title 3",
        img: "http://okitog.com/wp-content/uploads/2019/03/Sunset_Rocks_1X0A7279-1.jpg",
        desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit a atque laboriosam, et deleniti explicabo nisi nulla similique soluta? Fuga in cupiditate iure corporis cumque, cum temporibus obcaecati! Optio adipisci aspernatur, ad fugit obcaecati tenetur! Debitis sint illum consequuntur dolores, amet ut ullam impedit nulla reiciendis maiores asperiores voluptates natus iusto, inventore adipisci pariatur. Optio repellendus laborum est, maxime error quo modi perspiciatis officiis fugit nihil doloremque asperiores facere porro unde et. Odio ut optio animi harum rerum? Debitis, expedita non sit possimus repellat sint eos perferendis similique nesciunt, unde totam odio dolorum assumenda enim quidem ut voluptate fugiat distinctio!",
        longDesc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe amet nostrum atque ex iure non, similique quis, aperiam officiis, culpa nam! Necessitatibus delectus nisi inventore impedit consequuntur sed in voluptatum, beatae voluptas error nemo at distinctio eius ipsam! Nulla velit quis soluta atque consequatur illo blanditiis hic non quod eius accusantium, ducimus totam odio porro asperiores. Quasi at voluptates vero, id odio dolor optio distinctio soluta molestiae iste aspernatur inventore sequi, alias est, cumque praesentium impedit. Beatae, hic. Consequuntur quis minima rerum nemo vitae. Similique voluptatum distinctio eveniet ducimus autem ipsam, recusandae praesentium sed rem perspiciatis aliquam quae labore amet quia aliquid error incidunt necessitatibus! Sit voluptas nemo distinctio ipsum sint consequatur assumenda totam, quam veniam ut, aut est modi vero omnis earum laudantium? Inventore, iusto, temporibus dolorum quos tenetur iste cumque earum accusantium doloribus consectetur dolor libero! Doloribus, voluptatum! Commodi dignissimos cupiditate temporibus nesciunt aliquid obcaecati quam impedit eveniet necessitatibus vitae, velit, ea, sunt facere? Aliquid vitae id voluptates eos eum repellendus modi quae illum, dolor possimus velit veritatis accusantium officiis nemo nihil, quam quibusdam, nostrum magni fuga! Dolorem inventore amet eius aperiam numquam architecto rerum unde totam fugit vitae temporibus quo nulla ad, earum alias error illum nam laboriosam exercitationem consectetur minima possimus voluptas! Harum nesciunt facilis sint ipsum quidem ipsa. Quam, nemo, voluptas dolorum atque alias voluptate ipsa, quia libero ullam quaerat nostrum voluptates. Eius praesentium eligendi error repellendus sint quod numquam in, dicta atque blanditiis molestiae ea eaque voluptatibus facilis est maiores nisi veritatis earum fugiat, reprehenderit expedita odio officia. Error impedit commodi possimus inventore est, eveniet nostrum, iure ratione consequatur non debitis. Ea dignissimos dolorum alias pariatur magnam sequi voluptates commodi rerum nulla, nihil hic est dolores porro asperiores consequuntur aperiam, neque provident? Sunt nobis inventore quibusdam dicta ex soluta voluptatum in consequatur suscipit ea."
    },
];